language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
    
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/google-cloud-sdk/"  
  
before_script:
  # gcloud
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  # Add gcloud auth
  - gcloud auth activate-service-account firebase-adminsdk-mrzqn@expenses-ab252.iam.gserviceaccount.com --key-file=expenses-ab252-firebase-adminsdk-mrzqn-5aaabfed9d.json --project=expenses-ab252
  
script:
   - ./gradlew clean build check assembleDebugAndroidTest
   - N | gcloud firebase test android run --type instrumentation --results-bucket=gs://staging.expenses-ab252.appspot.com --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=sailfish,version=28,locale=en,orientation=portrait --environment-variables coverage=true,coverageFile="/sdcard/coverage.ec" --directories-to-pull /sdcard   
   

before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true
  - openssl aes-256-cbc -K $encrypted_4c13fe455862_key -iv $encrypted_4c13fe455862_iv -in expenses-ab252-firebase-adminsdk-mrzqn-5aaabfed9d.json.enc -out expenses-ab252-firebase-adminsdk-mrzqn-5aaabfed9d.json -d  