language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
 
script:
   - cat testLog
   - buildIdentifier="$(awk -F 'staging.expenses-ab252.appspot.com/' '{print $2}' testLog | awk '{print $1}' | cut -d'/' -f1)"
   - echo $buildIdentifier
