language: java
sudo: required

 
script:
   - echo "https://console.developers.google.com/storage/browser/staging.expenses-ab252.appspot.com/2019-02-27_20:37:04.848000_fYoq/]" | tee firebaseLog
   - cat firebaseLog
   - buildIdentifier="$(awk -F 'staging.expenses-ab252.appspot.com/' '{print $2}' firebaseLog | awk '{print $1}' | cut -d'/' -f1)"
   - echo $buildIdentifier

